
builds:
  # Custom environment variables to be set during the builds.
  # Default is empty.
- env:
    - CGO_ENABLED=0

  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
  ldflags:
    - -X "github.com/gomicro/train/cmd.Version={{.Env.TRAVIS_TAG}}"


  # GOOS list to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are darwin and linux.
  goos:
    - darwin
    - windows
    - linux
