[[constraint]]
  name = "github.com/certifi/gocertifi"
  version = "2018.1.18"

[[constraint]]
  name = "github.com/google/go-github"
  version = "28.1.1"

[[constraint]]
  name = "github.com/gosuri/uiprogress"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[prune]
  go-tests = true
  unused-packages = true
