name: Build
on: [push]

jobs:

  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}

    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: ./src/github.com/${{ github.repository }}

    - name: Test
      uses: gomicro/forge-action
      run: test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [linting, test]
    if: startsWith(github.ref, 'refs/tags/')

    env:
      GOPATH: ${{ github.workspace }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TRAIN_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
      TRAIN_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: ./src/github.com/${{ github.repository }}

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        install-only: true

    - name: Deploy
      working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
      run: make deploy
